apiVersion: v1
kind: Service
metadata:
  name: mssql-expose
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mssql-0
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 11433
