apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mssql-0
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
